export const SET_ACTIONS_TYPE = {
  SET_USER_TYPE: 'USER/SET_USER_TYPE',
  CHECK_USER_SESSION: 'USER/CHECK_USER_SESSION',
  GOOGLE_SIGN_IN_START: 'USER/GOOGLE_SIGN_IN_START',
  EMAIL_SIGN_IN_START: 'USER/EMAIL_SIGN_IN_START',
  SIGN_IN_SUCCESS: 'USER/SIGN_IN_SUCCESS',
  SIGN_IN_FAILED: 'USER/SIGN_IN_FAILED',
  SING_UP_START: 'USER/SING_UP_START',
  SIGN_UP_SUCCESS: 'USER/SIGN_UP_SUCCESS',
  SIGN_UP_FAILED: 'USER/SIGN_UP_FAILED',
};